---
- name: MOTD
  hosts: all
  remote_user: root
  gather_facts: no
  vars:
    MOTD_IMPORTANT: "Default Message"

  tasks:
    - name: Backup previous MOTD
      copy: remote_src=True src=/etc/motd dest=/etc/motd.bak

    - name: Setup a MOTD
      template:
        src: motdtemplate.j2
        dest: /etc/motd
        owner: root
        group: wheel
        mode: 0644

    - name: Restore the default a MOTD
      copy:
        remote_src: True
        src: /etc/motd.bak
        dest: /etc/motd
      tags:
        - rollback

