---
- name: MOTD
  hosts: all
  remote_user: root
  gather_facts: no
#  vars:
#    MOTD_IMPORTANT: "Default Message"

  tasks:
    - name: setup a MOTD
      template:
        src: motdtemplate.j2
        dest: /etc/motd
        owner: root
        group: wheel
        mode: 0644

